# Generated by Django 4.0.5 on 2022-06-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='drivfile',
            field=models.ImageField(default=1, max_length=254, upload_to='drive_liscence/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='drivingliscenceno',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
