# Generated by Django 3.1 on 2022-06-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_phonemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonemodel',
            name='Mobile',
            field=models.CharField(max_length=17),
        ),
    ]
