# Generated by Django 3.1 on 2022-06-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220621_1428'),
    ]

    operations = [
        migrations.DeleteModel(
            name='phoneModel',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
