# Generated by Django 4.0.5 on 2022-06-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='drivfile',
            field=models.ImageField(max_length=254, null=True, upload_to='drive_liscence/%Y/%m/%d'),
        ),
    ]
