# Generated by Django 4.0.5 on 2022-06-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_drivfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='drivingliscenceno',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
