# Generated by Django 4.0.5 on 2022-06-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0002_ride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='seat',
            field=models.PositiveIntegerField(),
        ),
    ]
