# Generated by Django 4.0.5 on 2022-06-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0006_alter_preferences_id_alter_ride_preferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='preferences',
        ),
        migrations.AddField(
            model_name='ride',
            name='music',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='pets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ride',
            name='smoking',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Preferences',
        ),
    ]
